version=0.1.0-SNAPSHOT
kotlin.code.style=official
kotlin.native.enableKlibsCrossCompilation=true
kotlin.native.ignoreDisabledTargets=true
# RawEvp.kt uses the OpenSSL cinterop bindings from the shared nativeMain source set
kotlin.mpp.enableCInteropCommonization=true

# gradle
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+UseParallelGC
org.gradle.configuration-cache=true
#org.gradle.configuration-cache.parallel=true
#org.gradle.caching=true
org.gradle.parallel=true
